"""Where a file came from, and where every document in it came from.

Two questions have to be answerable about anything in the system: who started
this file, and how did each document get into it. Until now the answer lived in
free text and JSON blobs that disagreed with each other — an operator's upload
was attributed to the client because the browser pre-filled the client's name in
the form, a field rep's upload through Capital OS was recorded as uploaded by
"Capital OS", and every upload wrote an audit row claiming the public lead did
it. None of that is recoverable after the fact, so this module gives both levels
a small server-decided vocabulary and one place to describe it in words.

The rule everywhere: the source is decided by the route from the authenticated
identity, never taken from the request body. A caller cannot claim to be a
client, and a form cannot claim to be an operator.
"""

from __future__ import annotations

from dataclasses import dataclass

# --- how a file was started ---------------------------------------------------

#: Every way a lead or client file comes into being.
FILE_SOURCES: dict[str, str] = {
    "public_form": "Public form",
    "internal_user": "Created internally",
    "field_rep": "Field rep",
    "dealer_partner": "Dealer partner",
    "booking": "Booking",
    "bucket_conversion": "Converted from a document room",
    "capital_os_handoff": "Capital OS handoff",
    "product_finder": "Product finder",
    "client_portal": "Client portal",
    "import": "Imported",
    "system": "System",
}

# --- how a document got in ----------------------------------------------------

#: Every way a document lands in a file. "internal_upload" covers anyone on the
#: desk; the rep and partner cases are separate because they are the ones the
#: trail could not answer before.
DOCUMENT_SOURCES: dict[str, str] = {
    "client_room": "Client uploaded in their room",
    "internal_upload": "Uploaded by the desk",
    "field_rep": "Uploaded by a field rep",
    "dealer_partner": "Uploaded by a dealer partner",
    "drive": "Imported from Google Drive",
    "zip_extract": "Extracted from an archive",
    "generated": "Generated by the system",
    "drafted_form": "Typed into a form",
    "esign": "Signature certificate",
    "vendor": "Delivered by a connected provider",
    "capital_os": "Mirrored from Capital OS",
    "email": "Arrived by email",
}

#: Sources where there is no human actor to record. A null user id on any other
#: source means the identity was lost, which is the thing this module exists to
#: stop, so the two cases must stay distinguishable.
UNATTENDED_SOURCES = frozenset({"generated", "vendor", "system"})

#: What the client themselves can be the source of. Anything else arriving with
#: a client actor is a bug in the calling route.
CLIENT_SOURCES = frozenset({"client_room", "email"})


@dataclass(frozen=True)
class Origin:
    """One resolved answer to "where did this come from"."""

    kind: str
    #: Display name of whoever did it, when there was a person.
    actor_name: str = ""
    #: Set only when the actor is a signed-in user of ours.
    actor_user_id: str | None = None
    #: Anything that names the specific route in: a Drive file, a vendor, an archive.
    detail: str = ""

    @property
    def label(self) -> str:
        return DOCUMENT_SOURCES.get(self.kind) or FILE_SOURCES.get(self.kind) or self.kind

    def describe(self) -> str:
        """One line for an operator: an email, an audit row, a file header."""
        parts = [self.label]
        if self.actor_name:
            parts.append(self.actor_name)
        if self.detail:
            parts.append(self.detail)
        return " · ".join(p for p in parts if p)


def file_origin(kind: str, *, actor=None, detail: str = "") -> Origin:
    """The origin of a lead or client file."""
    if kind not in FILE_SOURCES:
        raise ValueError(f"Unknown file source: {kind}")
    return _origin(kind, actor, detail)


def document_origin(kind: str, *, actor=None, detail: str = "") -> Origin:
    """The origin of one document in a file."""
    if kind not in DOCUMENT_SOURCES:
        raise ValueError(f"Unknown document source: {kind}")
    return _origin(kind, actor, detail)


def _origin(kind: str, actor, detail: str) -> Origin:
    name = ""
    user_id = None
    if actor is not None:
        name = (getattr(actor, "name", "") or getattr(actor, "email", "") or "").strip()
        raw_id = getattr(actor, "id", None)
        user_id = str(raw_id) if raw_id is not None else None
    return Origin(kind=kind, actor_name=name, actor_user_id=user_id, detail=(detail or "").strip()[:200])


def document_source_for(actor) -> str:
    """Which document source a signed-in user's upload is.

    The route decides this from the authenticated role, so a dealer's own upload
    in their portal is recorded as theirs and a rep's is recorded as the rep's —
    both used to arrive indistinguishable from the desk's.
    """
    role = str(getattr(actor, "role", "") or "")
    return {
        "field_rep": "field_rep",
        "dealer_partner": "dealer_partner",
        "broker": "dealer_partner",
        "client": "client_room",
        "dealer": "client_room",
    }.get(role, "internal_upload")


def actor_role_for(kind: str) -> str:
    """The audit-log actor_role that matches a source.

    Every intake upload used to log "public_lead" regardless of who did it, so an
    operator's upload claimed to be the borrower's. The role now follows the
    source the route decided.
    """
    return {
        "client_room": "public_lead",
        "email": "public_lead",
        "internal_upload": "operator",
        "field_rep": "field_rep",
        "dealer_partner": "dealer_partner",
        "drive": "operator",
        "zip_extract": "system",
        "generated": "system",
        "drafted_form": "operator",
        "esign": "system",
        "vendor": "system",
        "capital_os": "system",
    }.get(kind, "system")


def describe_document(row) -> str:
    """A human line for a stored document row, whatever it was stamped with.

    Rows written before provenance existed carry only display strings, so this
    degrades to what is there rather than claiming to know more than it does.
    """
    kind = (getattr(row, "source_kind", None) or "").strip()
    name = (getattr(row, "uploaded_by_name", "") or "").strip()
    detail = (getattr(row, "source_detail", "") or "").strip()
    if not kind:
        return f"Uploaded by {name}" if name else "Source not recorded"
    return Origin(kind=kind, actor_name=name, detail=detail).describe()


def describe_file(row) -> str:
    """A human line for how a lead or client file was started."""
    kind = (getattr(row, "source_kind", None) or "").strip()
    if not kind:
        return "Source not recorded"
    name = (getattr(row, "source_actor_name", "") or "").strip()
    detail = (getattr(row, "source_detail", "") or "").strip()
    return Origin(kind=kind, actor_name=name, detail=detail).describe()
