"""The client's room, and the link that reaches it.

Every request a rep makes of a business owner lands in the same place: the
bucket upload room, where they can read what is being asked of them, upload
documents, connect a bank and sign what needs signing. So there is one room per
file and one link to it, reused rather than reminted.

Reusing the link matters more than it looks. If every document request minted a
fresh token, an owner who kept the first email would find it dead by the time
they got round to it, and the third request would arrive with the first two
already invisible. One durable link means the last email is always the right
one, and so is the first.

The passcode is the exception. Staff choose it once while opening the file;
later replacements are generated by the server. It is only ever known in
plaintext at that moment because only its PBKDF2 hash is stored, so a reused
link cannot have its code recovered later. That is deliberate: a link that
reaches the wrong inbox is a much smaller problem when the code went to a
different channel or was read out loud.

Mechanics are copied from the bucket admin routes rather than reinvented, so
the room a rep opens behaves exactly like the room the desk opens.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import secrets
import time
from dataclasses import dataclass
from datetime import UTC

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.models.bucket import BucketRequestedDocument, BucketUploadLink
from app.services.provider_secrets import (
    _decrypt_fernet,
    _decrypt_kms,
    _encrypt_fernet,
    _encrypt_kms,
)

from ..models import DealerBusiness
from . import buckets_link

logger = logging.getLogger(__name__)

__all__ = [
    "ClientRoom",
    "ensure_room",
    "get_room",
    "initialize_room",
    "passcode_problem",
    "read_passcode",
    "request_document",
    "resolve_room",
    "room_url",
    "rotate_passcode",
    "set_passcode",
    "verify_passcode",
]

# Matches the bucket admin routes exactly. Changing either without the other
# would leave clients unable to open rooms created by the other surface.
_PBKDF2_ITERATIONS = 240_000


def _hash_passcode(passcode: str) -> str:
    salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256", passcode.encode("utf-8"), salt.encode("utf-8"), _PBKDF2_ITERATIONS
    ).hex()
    return f"pbkdf2_sha256${_PBKDF2_ITERATIONS}${salt}${digest}"


def _generate_passcode() -> str:
    return f"{secrets.randbelow(900000) + 100000}"


def _store_passcode(link: BucketUploadLink, passcode: str) -> None:
    """Replace the room credential and retain only encrypted recoverable text.

    The PBKDF2 hash remains the authentication source. The encrypted copy is
    used only by authenticated, file-scoped staff views.
    """
    settings = get_settings()
    link.passcode_hash = _hash_passcode(passcode)
    if settings.provider_secrets_kms_key_id:
        link.encrypted_passcode = _encrypt_kms(passcode)
        link.passcode_encryption_provider = "aws_kms"
    else:
        link.encrypted_passcode = _encrypt_fernet(passcode)
        link.passcode_encryption_provider = "fernet"


def read_passcode(link: BucketUploadLink) -> str | None:
    """Decrypt the current PIN for an already-authorized staff request."""
    if not link.encrypted_passcode:
        return None
    try:
        if link.passcode_encryption_provider == "aws_kms":
            value = _decrypt_kms(link.encrypted_passcode)
        else:
            value = _decrypt_fernet(link.encrypted_passcode)
    except Exception:
        logger.exception("dealer-os: could not decrypt client-room PIN for link %s", link.id)
        return None
    return value if len(value) == 6 and value.isascii() and value.isdigit() else None


def room_url(token: str) -> str:
    """The client-facing URL for a room token.

    The room is served by the main app, not by audit., because it predates
    Capital OS and every existing client link already points there.
    """
    settings = get_settings()
    base = (getattr(settings, "frontend_app_url", "") or "").rstrip("/")
    if settings.app_env.lower() == "production" and (
        not base or "localhost" in base or "127.0.0.1" in base or base.startswith("http://")
    ):
        base = "https://app.qualifiedcommercial.com"
    return f"{base}/buckets/request/{token}"


@dataclass
class ClientRoom:
    link: BucketUploadLink
    url: str
    # Plaintext only during initial setup or replacement. None for a reused
    # room because the stored hash cannot be reversed.
    passcode: str | None


async def _active_link(db: AsyncSession, bucket_id) -> BucketUploadLink | None:
    return (
        await db.execute(
            select(BucketUploadLink)
            .where(
                BucketUploadLink.bucket_id == bucket_id,
                BucketUploadLink.status == "active",
            )
            .order_by(BucketUploadLink.created_at.desc())
            .limit(1)
        )
    ).scalar_one_or_none()


async def get_room(db: AsyncSession, dealer: DealerBusiness) -> ClientRoom | None:
    """Return the durable room without creating or rotating credentials."""
    if dealer.bucket_id is None:
        return None
    link = await _active_link(db, dealer.bucket_id)
    if link is None:
        return None
    return ClientRoom(link, room_url(link.token), None)


async def initialize_room(
    db: AsyncSession,
    dealer: DealerBusiness,
    passcode: str,
) -> ClientRoom:
    """Create the file room with its one-time, staff-chosen initial PIN.

    This is called only from the file-creation transaction. No later endpoint
    accepts a caller-provided PIN; replacements are generated by the server.
    """
    if len(passcode) != 6 or not passcode.isascii() or not passcode.isdigit():
        raise ValueError("The secure client-room PIN must contain six digits.")
    bucket = await buckets_link.ensure_bucket(db, dealer)
    link = await _active_link(db, bucket.id)
    if link is None:
        link = BucketUploadLink(
            bucket_id=bucket.id,
            token=secrets.token_urlsafe(32),
            recipient_name=(dealer.name or "Business owner")[:180],
            recipient_email=(dealer.email or None),
            expires_at=None,
        )
        _store_passcode(link, passcode)
        db.add(link)
    else:
        # A newly opened file can adopt a pre-existing intake bucket. Initial
        # setup deliberately replaces that old room credential exactly once.
        _store_passcode(link, passcode)
        link.expires_at = None
        link.recipient_name = (dealer.name or link.recipient_name)[:180]
        link.recipient_email = dealer.email or link.recipient_email
    await db.flush()
    logger.info("dealer-os: initialized client room %s for dealer %s", link.id, dealer.id)
    return ClientRoom(link, room_url(link.token), passcode)


async def ensure_room(
    db: AsyncSession, dealer: DealerBusiness, *, adopt_intake: bool = True
) -> ClientRoom:
    """The file's client room, created if it does not exist yet. Flushes, never commits."""
    bucket = await buckets_link.ensure_bucket(db, dealer, adopt_intake=adopt_intake)

    link = await _active_link(db, bucket.id)
    if link is not None:
        return ClientRoom(link, room_url(link.token), None)

    passcode = _generate_passcode()
    link = BucketUploadLink(
        bucket_id=bucket.id,
        token=secrets.token_urlsafe(32),
        recipient_name=(dealer.name or "Business owner")[:180],
        recipient_email=(dealer.email or None),
        expires_at=None,
    )
    _store_passcode(link, passcode)
    db.add(link)
    await db.flush()
    logger.info("dealer-os: opened client room %s for dealer %s", link.id, dealer.id)
    return ClientRoom(link, room_url(link.token), passcode)


async def request_document(
    db: AsyncSession,
    dealer: DealerBusiness,
    *,
    name: str,
    description: str | None = None,
    category: str | None = None,
    requires_signature: bool = False,
    signature_kind: str | None = None,
    signature_document_text: str | None = None,
    required: bool = True,
) -> BucketRequestedDocument:
    """Put an item on the client's checklist. Flushes, never commits.

    Signature requests are the same object with `requires_signature` set, which
    is what the existing signing flow keys off. Modelling them as a separate
    thing would mean two checklists for the client to work through and two
    places to notice that something is still outstanding.
    """
    bucket = await buckets_link.ensure_bucket(db, dealer)

    # An identical open request is a duplicate, not a second ask. Reps re-send
    # reminders, and a checklist that grows a new row each time is one the
    # client stops reading.
    existing = (
        await db.execute(
            select(BucketRequestedDocument).where(
                BucketRequestedDocument.bucket_id == bucket.id,
                BucketRequestedDocument.name == name,
            )
        )
    ).scalar_one_or_none()
    if existing is not None:
        if description and not existing.description:
            existing.description = description
        # A signature request adopting a same-named plain row must UPGRADE it,
        # or the signature requirement silently vanishes: the room would show
        # an upload row, the client would attach any file, and the rep would
        # see the item satisfied with nothing signed.
        if requires_signature and not existing.requires_signature:
            existing.requires_signature = True
            existing.signature_kind = signature_kind
            existing.signature_document_text = signature_document_text
        await db.flush()
        return existing

    doc = BucketRequestedDocument(
        bucket_id=bucket.id,
        name=name,
        category=category,
        description=description,
        required=required,
        is_custom=True,
        requires_signature=requires_signature,
        signature_kind=signature_kind,
        signature_document_text=signature_document_text,
    )
    db.add(doc)
    await db.flush()
    return doc


async def rotate_passcode(db: AsyncSession, dealer: DealerBusiness) -> ClientRoom:
    """A fresh access code for the file's room, returned in plaintext once.

    The stored code is a PBKDF2 hash and can never be re-displayed, which is
    the right storage and a wrong dead end: a rep who missed the one-time
    display used to have a client locked out of their own room. Rotation is
    the answer — mint a new code, invalidate the old, read the new one out.
    One code then covers everything the room does: uploads, bank connection,
    credit authorization, signing.
    """
    room = await ensure_room(db, dealer)
    passcode = _generate_passcode()
    _store_passcode(room.link, passcode)
    room.link.expires_at = None
    # A rep-issued code is a generated one again: the room offers the client
    # the chance to choose their own on the next entry.
    room.link.passcode_set_by_client_at = None
    await db.flush()
    logger.info("dealer-os: room passcode rotated for dealer %s", dealer.id)
    return ClientRoom(room.link, room.url, passcode)


#: Codes nobody should be allowed to choose. Six digits is a small space
#: already; these are the ones a guesser tries first.
_TRIVIAL_PASSCODES = frozenset(
    {f"{d}{d}{d}{d}{d}{d}" for d in "0123456789"}
    | {"123456", "654321", "012345", "543210", "123123", "112233", "121212", "111222"}
)


def passcode_problem(new_passcode: str, current_passcode: str | None = None) -> str | None:
    """Why a client-chosen PIN is not acceptable, or None when it is."""
    code = (new_passcode or "").strip()
    if len(code) != 6 or not code.isdigit():
        return "Choose a 6-digit PIN."
    if code in _TRIVIAL_PASSCODES:
        return "That PIN is too easy to guess. Choose six digits that are not all the same or in a row."
    if current_passcode is not None and code == current_passcode.strip():
        return "Choose a PIN that is different from the one we sent you."
    return None


async def set_passcode(db: AsyncSession, link: BucketUploadLink, new_passcode: str) -> None:
    """The client replaces the generated PIN with one they will remember.

    Stored exactly like a generated code (hash + recoverable encrypted copy),
    so nothing downstream can tell the difference; the stamp only tells the
    room to stop offering the change. Flushes, never commits.
    """
    from datetime import datetime

    _store_passcode(link, new_passcode.strip())
    link.passcode_set_by_client_at = datetime.now(UTC)
    await db.flush()
    logger.info("dealer-os: room passcode chosen by client link=%s", link.id)


# --- opening the room from the client's side ---------------------------------

# Same lockout the bucket routes use, and for the same reason: a generated
# passcode is six digits, so a leaked link URL would otherwise be brute-forced
# by enumerating 900k codes. In-process counter, single-instance assumption,
# matching the existing throttles.
_ATTEMPTS: dict[str, tuple[int, float]] = {}
_MAX_ATTEMPTS = 10
_LOCKOUT_SECONDS = 900.0


def _locked(key: str) -> bool:
    entry = _ATTEMPTS.get(key)
    if not entry:
        return False
    attempts, until = entry
    if attempts < _MAX_ATTEMPTS:
        return False
    if time.monotonic() >= until:
        _ATTEMPTS.pop(key, None)  # window elapsed, allow a fresh burst
        return False
    return True


def verify_passcode(passcode: str, passcode_hash: str | None) -> bool:
    """Constant-time check with lockout. Mirrors the bucket routes exactly, so
    a room opened from either surface behaves the same."""
    if not passcode_hash:
        return False
    if _locked(passcode_hash):
        return False
    try:
        scheme, raw_iterations, salt, expected = passcode_hash.split("$", 3)
        if scheme != "pbkdf2_sha256":
            return False
        iterations = int(raw_iterations)
    except ValueError:
        return False
    digest = hashlib.pbkdf2_hmac(
        "sha256", passcode.encode("utf-8"), salt.encode("utf-8"), iterations
    ).hex()
    if hmac.compare_digest(digest, expected):
        _ATTEMPTS.pop(passcode_hash, None)  # success resets the counter
        return True
    attempts = _ATTEMPTS.get(passcode_hash, (0, 0.0))[0] + 1
    _ATTEMPTS[passcode_hash] = (attempts, time.monotonic() + _LOCKOUT_SECONDS)
    return False


async def resolve_room(
    db: AsyncSession, token: str, passcode: str
) -> tuple[BucketUploadLink, DealerBusiness]:
    """Turn a room token and passcode into the one file it belongs to.

    This is the whole security model for the unauthenticated endpoints, so it
    is worth being explicit about what it guarantees. The caller never names a
    dealer: the dealer is derived from the token. A token issued for file A
    therefore cannot be used to write into file B, because there is no
    parameter in which to say "B". Combined with the passcode and its lockout,
    a leaked URL alone is not enough, and a leaked URL plus unlimited guessing
    is not either.

    Raises LookupError for anything that fails, so callers cannot accidentally
    distinguish "wrong token" from "wrong code" and turn this into an oracle.
    """
    from datetime import datetime

    link = (
        await db.execute(select(BucketUploadLink).where(BucketUploadLink.token == token))
    ).scalar_one_or_none()
    if link is None or link.status != "active":
        raise LookupError("room not found")
    if link.expires_at is not None and link.expires_at < datetime.now(UTC):
        raise LookupError("room not found")
    if not verify_passcode(passcode or "", link.passcode_hash):
        raise LookupError("room not found")

    dealer = (
        await db.execute(
            select(DealerBusiness).where(DealerBusiness.bucket_id == link.bucket_id)
        )
    ).scalar_one_or_none()
    if dealer is None:
        # A bucket with no Capital OS file behind it is an intake-only room.
        # There is nothing to connect a bank to, and saying so plainly beats
        # a confusing Plaid error.
        raise LookupError("this room is not attached to a funding file")
    return link, dealer
