"""One-time post-process: renames the auto-generated blank placeholder names
in app/services/contract_templates_data.py (client_engagement_blank_amount_3,
etc.) to clean, human-readable field names/labels/types, using the rename
maps produced by the field-naming Workflow (propose+verify per document,
saved under C:/Users/franc/AppData/Local/Temp/qc_contracts/renames/*.json)
plus a small manual addition set for the cover-block fields that workflow
never saw (client_legal_name, effective_date, etc. -- added to the parser
after the workflow ran).

Does NOT touch legal prose: only the $placeholder token names are renamed,
everywhere they appear (field_schema keys + every $old_name occurrence in
cover/notice/preamble/section paragraphs), via a single-pass, name-boundary-
safe regex substitution -- same approach already proven correct in
scripts/verify_content_fidelity.py.

Usage: python scripts/apply_contract_field_renames.py
Reads app/services/contract_templates_data.py (must already be freshly
regenerated by build_contract_templates.py) + the rename JSON files.
Overwrites app/services/contract_templates_data.py in place.
"""

from __future__ import annotations

import importlib.util
import json
import pprint
import re
from pathlib import Path

RENAMES_DIR = Path("C:/Users/franc/AppData/Local/Temp/qc_contracts/renames")
MANUAL_ADDITIONS = Path("C:/Users/franc/AppData/Local/Temp/qc_apply/manual_additions.json")
DATA_FILE = Path(__file__).resolve().parent.parent / "app" / "services" / "contract_templates_data.py"

DOCS = ["client_engagement", "sba_engagement", "referral_protection", "platform_access", "consulting_addendum"]


def load_raw_data() -> dict:
    spec = importlib.util.spec_from_file_location("contract_templates_data", DATA_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    return mod.CONTRACT_RAW_DATA


def load_rename_map(doc_key: str) -> dict[str, dict]:
    with (RENAMES_DIR / f"{doc_key}.json").open(encoding="utf-8") as f:
        proposed = json.load(f)["renames"]
    with MANUAL_ADDITIONS.open(encoding="utf-8") as f:
        manual = json.load(f)[doc_key]
    by_old_name: dict[str, dict] = {}
    for entry in proposed + manual:
        by_old_name[entry["old_name"]] = entry
    return by_old_name


def substitute_tokens(text: str, rename_map: dict[str, dict]) -> str:
    def repl(m: "re.Match") -> str:
        old_name = m.group(1)
        entry = rename_map.get(old_name)
        return f"${entry['new_name']}" if entry else m.group(0)

    return re.sub(r"\$([A-Za-z0-9_]+)", repl, text)


def rename_document(doc_key: str, doc: dict, rename_map: dict[str, dict]) -> dict:
    actual_keys = set(doc["field_schema"].keys())
    mapped_keys = set(rename_map.keys())
    if actual_keys != mapped_keys:
        raise ValueError(
            f"{doc_key}: rename map does not exactly cover field_schema keys.\n"
            f"  missing from rename map: {actual_keys - mapped_keys}\n"
            f"  extra in rename map (not in field_schema): {mapped_keys - actual_keys}"
        )

    new_field_schema: dict = {}
    for old_name, info in doc["field_schema"].items():
        entry = rename_map[old_name]
        new_field_schema[entry["new_name"]] = {
            "label": entry["label"],
            "default": entry.get("default") or info.get("default", ""),
            "raw_token": info["raw_token"],
            "field_type": entry.get("field_type", "text"),
            "row_group": entry.get("row_group"),
            "in_scope_for_initial_signing": entry.get("in_scope_for_initial_signing", True),
        }

    def sub(t: str) -> str:
        return substitute_tokens(t, rename_map)

    return {
        "cover": [sub(p) for p in doc["cover"]],
        "notice": sub(doc["notice"]) if doc["notice"] else None,
        "internal_notice": doc["internal_notice"],
        "preamble": [sub(p) for p in doc["preamble"]],
        "sections": [{"heading": s["heading"], "paragraphs": [sub(p) for p in s["paragraphs"]]} for s in doc["sections"]],
        "field_schema": new_field_schema,
    }


if __name__ == "__main__":
    raw_data = load_raw_data()
    results = {}
    for doc_key in DOCS:
        rename_map = load_rename_map(doc_key)
        results[doc_key] = rename_document(doc_key, raw_data[doc_key], rename_map)
        print(f"{doc_key}: renamed {len(rename_map)} fields")

    with DATA_FILE.open("w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/build_contract_templates.py + \n')
        f.write("scripts/apply_contract_field_renames.py from the source .docx contract\n")
        f.write("text. Do not hand-edit generated dict literals directly here -- change\n")
        f.write("contract_templates.py's post-processing instead, or re-run the generator\n")
        f.write('against a corrected source .txt.\n"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("CONTRACT_RAW_DATA: dict = ")
        f.write(pprint.pformat(results, indent=2, width=100, sort_dicts=False))
        f.write("\n")
    print(f"Wrote {DATA_FILE}")
