"""Codegen — emit a TypeScript enums file into both frontends.

Single source of truth: app/enums.py. Re-run after editing enums:

    python -m uv run python scripts/gen_ts_enums.py
"""

from __future__ import annotations

from enum import EnumMeta
from pathlib import Path
from textwrap import dedent

from app import enums as enum_module
from app.constants import (
    DSCR_MAX_LTV_CASH_OUT,
    DSCR_MAX_LTV_PURCHASE,
    DSCR_MIN_FICO,
    DSCR_MIN_RATIO_PREFERRED,
    DSCR_MIN_RATIO_STANDARD,
    FF_MAX_ARV_LTV,
    FF_MAX_LTC,
    FF_TERM_MAX_MONTHS,
    FF_TERM_MIN_MONTHS,
    SOFT_PULL_VALIDITY_DAYS,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGETS = [
    REPO_ROOT / "qcdesktop" / "src" / "lib" / "enums.generated.ts",
    REPO_ROOT / "qcmobile" / "src" / "lib" / "enums.generated.ts",
]


def _humanize(v: str) -> str:
    return v.replace("_", " ").title()


def emit() -> str:
    parts: list[str] = [
        "// AUTOGENERATED by qcbackend/scripts/gen_ts_enums.py — do not hand-edit.",
        "// Re-run when app/enums.py or app/constants.py change.",
        "",
    ]
    for name in sorted(dir(enum_module)):
        obj = getattr(enum_module, name)
        if not isinstance(obj, EnumMeta):
            continue
        # `as const` object so members have string-literal types
        body = ",\n".join(f'  {m.name}: "{m.value}"' for m in obj)
        parts.append(f"export const {name} = {{\n{body}\n}} as const;")
        parts.append(
            f"export type {name} = (typeof {name})[keyof typeof {name}];"
        )
        opts = ",\n".join(
            f'  {{ value: "{m.value}", label: "{_humanize(m.value)}" }}' for m in obj
        )
        parts.append(f"export const {name}Options = [\n{opts}\n] as const;")
        parts.append("")

    parts.append(
        dedent(
            f"""
            export const LendingLimits = {{
              dscrMaxLtvPurchase: {DSCR_MAX_LTV_PURCHASE},
              dscrMaxLtvCashOut: {DSCR_MAX_LTV_CASH_OUT},
              dscrMinFico: {DSCR_MIN_FICO},
              dscrMinRatioStandard: {DSCR_MIN_RATIO_STANDARD},
              dscrMinRatioPreferred: {DSCR_MIN_RATIO_PREFERRED},
              ffMaxLtc: {FF_MAX_LTC},
              ffMaxArvLtv: {FF_MAX_ARV_LTV},
              ffTermMinMonths: {FF_TERM_MIN_MONTHS},
              ffTermMaxMonths: {FF_TERM_MAX_MONTHS},
              softPullValidityDays: {SOFT_PULL_VALIDITY_DAYS},
            }} as const;
            """
        ).strip()
    )
    return "\n".join(parts) + "\n"


def main() -> None:
    code = emit()
    for target in TARGETS:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(code, encoding="utf-8")
        print(f"Wrote {target}")


if __name__ == "__main__":
    main()
