"""One-time patch: Schedule B's per-product retainer amounts in the
referral_protection template are Qualified Commercial's own standard
pricing, not something a referral-partner counterparty elects on the public
portal. Confirmed with the business owner: $2,500 for the 3 program-capped
products (SBA 7(a)/Express, SBA 504, USDA B&I) and a flat $5,000 for the 6
non-program-capped products (CRE/DSCR, Dealer Floorplan, Warranty/
Reinsurance, Asset-Based Lending, Bridge/Private Credit, Working Capital).
The "Other" product row and the optional per-transaction fee cap are left
unset (blank default, out of scope) -- deferred per the business owner's
own choice, not a data gap.

Sets fixed defaults and marks all Schedule B retainer/cap fields out of
scope for initial signing so they never render as fillable inputs on the
public portal.

Usage: python scripts/patch_schedule_b_retainer_defaults.py
Edits app/services/contract_templates_data.py in place.
"""

from __future__ import annotations

import importlib.util
import pprint
from pathlib import Path

DATA_FILE = Path(__file__).resolve().parent.parent / "app" / "services" / "contract_templates_data.py"

PROGRAM_CAPPED_RETAINER = "2500"
STANDARD_RETAINER = "5000"

RETAINER_FIELD_DEFAULTS = {
    "schedule_b_retainer_sba_7a_express": PROGRAM_CAPPED_RETAINER,
    "schedule_b_retainer_sba_504": PROGRAM_CAPPED_RETAINER,
    "schedule_b_retainer_usda_bi": PROGRAM_CAPPED_RETAINER,
    "schedule_b_retainer_cre_dscr": STANDARD_RETAINER,
    "schedule_b_retainer_dealer_floorplan": STANDARD_RETAINER,
    "schedule_b_retainer_warranty_reinsurance": STANDARD_RETAINER,
    "schedule_b_retainer_asset_based_lending": STANDARD_RETAINER,
    "schedule_b_retainer_bridge_private_credit": STANDARD_RETAINER,
    "schedule_b_retainer_working_capital_loc": STANDARD_RETAINER,
}

# Left blank (deferred) per the business owner's own choice -- not defaulted.
OUT_OF_SCOPE_ONLY = [
    "schedule_b_other_product_name",
    "schedule_b_other_fee_rate_low",
    "schedule_b_other_fee_rate_high",
    "schedule_b_other_retainer",
    "schedule_b_max_fee_per_transaction",
]

if __name__ == "__main__":
    spec = importlib.util.spec_from_file_location("contract_templates_data", DATA_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    data = mod.CONTRACT_RAW_DATA

    fs = data["referral_protection"]["field_schema"]
    for name, default in RETAINER_FIELD_DEFAULTS.items():
        fs[name]["default"] = default
        fs[name]["in_scope_for_initial_signing"] = False
        print(f"referral_protection.{name} default -> {default!r}, in_scope_for_initial_signing -> False")
    for name in OUT_OF_SCOPE_ONLY:
        fs[name]["in_scope_for_initial_signing"] = False
        print(f"referral_protection.{name} in_scope_for_initial_signing -> False (left blank)")

    with DATA_FILE.open("w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/build_contract_templates.py + \n')
        f.write("scripts/apply_contract_field_renames.py + \n")
        f.write("scripts/patch_qc_own_field_defaults.py + \n")
        f.write("scripts/patch_venue_county_default.py + \n")
        f.write("scripts/patch_schedule_b_retainer_defaults.py from the source .docx contract\n")
        f.write("text. Do not hand-edit generated dict literals directly here -- change\n")
        f.write("contract_templates.py's post-processing instead, or re-run the generator\n")
        f.write('against a corrected source .txt.\n"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("CONTRACT_RAW_DATA: dict = ")
        f.write(pprint.pformat(data, indent=2, width=100, sort_dicts=False))
        f.write("\n")
    print(f"Wrote {DATA_FILE}")
