"""One-time patch: the NJ Superior Court venue-county blank in 4 of the 5
contract templates (client_engagement, sba_engagement, referral_protection,
platform_access) is Qualified Commercial's own choice of litigation forum,
not a counterparty election -- confirmed with the business owner (Bergen
County). Sets a fixed default so render_contract_document() fills it
automatically and marks it out of scope for initial signing so it's never
presented as a fillable field on the public portal or any signing form.

Usage: python scripts/patch_venue_county_default.py
Edits app/services/contract_templates_data.py in place.
"""

from __future__ import annotations

import importlib.util
import pprint
from pathlib import Path

DATA_FILE = Path(__file__).resolve().parent.parent / "app" / "services" / "contract_templates_data.py"

VENUE_COUNTY_FIELD_BY_DOC = {
    "client_engagement": "venue_county",
    "sba_engagement": "venue_county",
    "referral_protection": "venue_county",
    "platform_access": "nj_venue_county",
}

if __name__ == "__main__":
    spec = importlib.util.spec_from_file_location("contract_templates_data", DATA_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    data = mod.CONTRACT_RAW_DATA

    for doc_key, field_name in VENUE_COUNTY_FIELD_BY_DOC.items():
        fs = data[doc_key]["field_schema"]
        fs[field_name]["default"] = "Bergen"
        fs[field_name]["in_scope_for_initial_signing"] = False
        print(f"{doc_key}.{field_name} default -> 'Bergen', in_scope_for_initial_signing -> False")

    with DATA_FILE.open("w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/build_contract_templates.py + \n')
        f.write("scripts/apply_contract_field_renames.py + \n")
        f.write("scripts/patch_qc_own_field_defaults.py + \n")
        f.write("scripts/patch_venue_county_default.py from the source .docx contract\n")
        f.write("text. Do not hand-edit generated dict literals directly here -- change\n")
        f.write("contract_templates.py's post-processing instead, or re-run the generator\n")
        f.write('against a corrected source .txt.\n"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("CONTRACT_RAW_DATA: dict = ")
        f.write(pprint.pformat(data, indent=2, width=100, sort_dicts=False))
        f.write("\n")
    print(f"Wrote {DATA_FILE}")
