"""One-time patch: Qualified Commercial's own notice-block fields (its
principal address, notice Attn/email/counsel-copy) already have real fixed
defaults set by patch_qc_own_field_defaults.py -- they should never be
presented to a signer as fillable inputs either, same treatment as the
venue-county and Schedule B retainer fields. Marks them out of scope for
initial signing.

Usage: python scripts/patch_qc_own_fields_out_of_scope.py
Edits app/services/contract_templates_data.py in place.
"""

from __future__ import annotations

import importlib.util
import pprint
from pathlib import Path

DATA_FILE = Path(__file__).resolve().parent.parent / "app" / "services" / "contract_templates_data.py"

QC_OWN_FIELDS = [
    "qc_principal_place_of_business",
    "qc_notice_attn",
    "qc_notice_address_line1",
    "qc_notice_address_line2",
    "qc_notice_email",
    "qc_notice_counsel_copy",
]

if __name__ == "__main__":
    spec = importlib.util.spec_from_file_location("contract_templates_data", DATA_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    data = mod.CONTRACT_RAW_DATA

    fs = data["referral_protection"]["field_schema"]
    for name in QC_OWN_FIELDS:
        fs[name]["in_scope_for_initial_signing"] = False
        print(f"referral_protection.{name} in_scope_for_initial_signing -> False")

    with DATA_FILE.open("w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/build_contract_templates.py + \n')
        f.write("scripts/apply_contract_field_renames.py + \n")
        f.write("scripts/patch_qc_own_field_defaults.py + \n")
        f.write("scripts/patch_venue_county_default.py + \n")
        f.write("scripts/patch_schedule_b_retainer_defaults.py + \n")
        f.write("scripts/patch_qc_own_fields_out_of_scope.py from the source .docx contract\n")
        f.write("text. Do not hand-edit generated dict literals directly here -- change\n")
        f.write("contract_templates.py's post-processing instead, or re-run the generator\n")
        f.write('against a corrected source .txt.\n"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("CONTRACT_RAW_DATA: dict = ")
        f.write(pprint.pformat(data, indent=2, width=100, sort_dicts=False))
        f.write("\n")
    print(f"Wrote {DATA_FILE}")
