"""One-time patch: Qualified Commercial's own notice-block fields in the
referral_protection template (its own principal address, notice Attn/email)
should never be blank inputs on the public portal -- QC is one of the two
fixed parties to every Referral Protection Agreement, so its own contact
details are known constants, not something a signer fills in. This sets
real default values for those fields in field_schema so
render_contract_document() fills them automatically even when the portal
omits them from field_values, and the portal never asks a signer for QC's
own address.

Usage: python scripts/patch_qc_own_field_defaults.py
Edits app/services/contract_templates_data.py in place.
"""

from __future__ import annotations

import importlib.util
import pprint
from pathlib import Path

DATA_FILE = Path(__file__).resolve().parent.parent / "app" / "services" / "contract_templates_data.py"

QC_FIELD_DEFAULTS = {
    "qc_principal_place_of_business": "14 53rd St #408N, Brooklyn, NY 11232",
    "qc_notice_attn": "Jonathan Franco, Executive Partner",
    "qc_notice_address_line1": "14 53rd St #408N",
    "qc_notice_address_line2": "Brooklyn, NY 11232",
    "qc_notice_email": "support@qualifiedcommercial.com",
    "qc_notice_counsel_copy": "N/A",
}

if __name__ == "__main__":
    spec = importlib.util.spec_from_file_location("contract_templates_data", DATA_FILE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore
    data = mod.CONTRACT_RAW_DATA

    fs = data["referral_protection"]["field_schema"]
    for name, default in QC_FIELD_DEFAULTS.items():
        fs[name]["default"] = default
        print(f"referral_protection.{name} default -> {default!r}")

    with DATA_FILE.open("w", encoding="utf-8") as f:
        f.write('"""Auto-generated by scripts/build_contract_templates.py + \n')
        f.write("scripts/apply_contract_field_renames.py + \n")
        f.write("scripts/patch_qc_own_field_defaults.py from the source .docx contract\n")
        f.write("text. Do not hand-edit generated dict literals directly here -- change\n")
        f.write("contract_templates.py's post-processing instead, or re-run the generator\n")
        f.write('against a corrected source .txt.\n"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("CONTRACT_RAW_DATA: dict = ")
        f.write(pprint.pformat(data, indent=2, width=100, sort_dicts=False))
        f.write("\n")
    print(f"Wrote {DATA_FILE}")
