from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base
from app.enums import DealHealth, LoanPurpose, LoanStage, LoanType, PropertyType
from app.models._mixins import TimestampMixin

if TYPE_CHECKING:
    from app.models.activity import Activity
    from app.models.ai_task import AITask
    from app.models.client import Client
    from app.models.document import Document
    from app.models.email_draft import EmailDraft
    from app.models.event import CalendarEvent
    from app.models.hud import HudLineItem
    from app.models.lender import Lender
    from app.models.loan_participant import LoanParticipant
    from app.models.message import Message
    from app.models.prequal_request import PrequalRequest


class Loan(TimestampMixin, Base):
    __tablename__ = "loans"

    id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Human-friendly deal ID — used in email subject [QC-{deal_id}]
    deal_id: Mapped[str] = mapped_column(String(16), unique=True, index=True, nullable=False)

    client_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("clients.id", ondelete="CASCADE")
    )
    broker_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("brokers.id", ondelete="SET NULL"), nullable=True
    )
    # Connected lender — set when the operator runs the Connect-Lender
    # flow. Adding a row here also creates a hide_identity=True
    # LoanParticipant for the lender, which is what the orchestrator's
    # Gateway Rule machinery actually keys off.
    lender_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("lenders.id", ondelete="SET NULL"), nullable=True
    )

    # Property
    address: Mapped[str] = mapped_column(String(320), nullable=False)
    city: Mapped[str | None] = mapped_column(String(160), nullable=True)
    property_type: Mapped[PropertyType] = mapped_column(String(32), default=PropertyType.SFR)
    sqft: Mapped[int | None] = mapped_column(Integer, nullable=True)
    beds: Mapped[int | None] = mapped_column(Integer, nullable=True)
    baths: Mapped[float | None] = mapped_column(Numeric(4, 1), nullable=True)
    year_built: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Number of dwelling units on the property. Drives the
    # per-unit fan-out in the doc checklist (one Lease per unit on a
    # 4-plex, etc.) and surfaces as a column on the Property
    # Details tab. Defaults to 1 so legacy rows behave like SFRs.
    unit_count: Mapped[int | None] = mapped_column(Integer, nullable=True, default=1)
    annual_taxes: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    annual_insurance: Mapped[float] = mapped_column(Numeric(12, 2), default=0)
    monthly_hoa: Mapped[float] = mapped_column(Numeric(10, 2), default=0)

    # Loan
    type: Mapped[LoanType] = mapped_column(String(32), nullable=False)
    purpose: Mapped[LoanPurpose | None] = mapped_column(String(32), nullable=True)
    stage: Mapped[LoanStage] = mapped_column(String(32), default=LoanStage.PREQUALIFIED)
    amount: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    ltv: Mapped[float | None] = mapped_column(Numeric(6, 4), nullable=True)
    ltc: Mapped[float | None] = mapped_column(Numeric(6, 4), nullable=True)
    arv: Mapped[float | None] = mapped_column(Numeric(14, 2), nullable=True)
    base_rate: Mapped[float | None] = mapped_column(Numeric(7, 6), nullable=True)
    discount_points: Mapped[float] = mapped_column(Numeric(5, 3), default=0)
    final_rate: Mapped[float | None] = mapped_column(Numeric(7, 6), nullable=True)
    origination_pct: Mapped[float] = mapped_column(Numeric(6, 4), default=0.015)
    term_months: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Underwriting
    monthly_rent: Mapped[float | None] = mapped_column(Numeric(12, 2), nullable=True)
    dscr: Mapped[float | None] = mapped_column(Numeric(8, 4), nullable=True)
    risk_score: Mapped[int | None] = mapped_column(Integer, nullable=True)

    close_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # Living Loan File — generated by app.services.ai.summarizer after every
    # activity event. Always reflects the current state of the deal.
    status_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    deal_health: Mapped[DealHealth] = mapped_column(String(32), default=DealHealth.ON_TRACK, nullable=False)
    # Structured "Living Loan Profile" produced by 'The Associate' summarizer.
    # Shape: {current_status, market_context, bottlenecks, next_actions} —
    # see app/services/ai/summarizer.py and app/schemas/loan.LivingLoanProfile.
    # Nullable so older loans without a refresh still load.
    living_profile: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # Phase 6 — debounced Living Loan File refresh. log_activity() flips
    # `summary_dirty=True` whenever a router writes an Activity row for
    # this loan; the scheduler's job_summary_dirty_drain picks dirty
    # loans up every 5 min and runs the summarizer. `summary_refreshed_at`
    # records the last successful drain so the UI can show staleness
    # ("updated 3 min ago"). Both columns added in alembic 0013.
    summary_dirty: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )
    summary_refreshed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Deal Workspace — when set, the AI auto-reply path skips this loan until
    # the timestamp passes. Set to now()+1h whenever a super-admin sends a
    # manual message in the client thread (handled in routers/loan_workspace.py).
    ai_paused_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Set by the AI's `complete_property_intake` tool once enough
    # property facts have been gathered (beds/baths/sqft/units/year).
    # The intake opener stops asking once this is set; the chat moves
    # on to doc collection.
    intake_complete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    client: Mapped[Client] = relationship(back_populates="loans")
    lender: Mapped["Lender | None"] = relationship(back_populates="loans")
    documents: Mapped[list[Document]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    hud_items: Mapped[list[HudLineItem]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    activities: Mapped[list[Activity]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    messages: Mapped[list[Message]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    ai_tasks: Mapped[list[AITask]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    calendar_events: Mapped[list[CalendarEvent]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    participants: Mapped[list[LoanParticipant]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    email_drafts: Mapped[list[EmailDraft]] = relationship(back_populates="loan", cascade="all, delete-orphan")
    prequal_requests: Mapped[list[PrequalRequest]] = relationship(back_populates="loan", cascade="all, delete-orphan")
